defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: Eddie
  host: localhost


development:
  <<: *defaults
  database: brightfutures_development

test:
  <<: *defaults
  database: brightfutures_test

production:
  <<: *defaults
  database: brightfutures_production
