defaults: &defaults
  google:
    maps_key: AIzaSyCR-mruRiXKCWnEVNWyxWt0So5YTNrlYOE
  facebook:
    app_id: 150757598452774
    app_secret: 80688b8bfef4e5c881dd5b635d54eca9
  google:
    maps_key: AIzaSyC5nbu6QghhMZ7nUg8KppPc--tPG1QFWkA
  stripe:
    private_key: sk_test_1XLNZlt83RDDPqRIO7EiWoCm
    public_key: pk_test_B86VL4gz8MTalpfcaRc4paiP

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults
  facebook:
    app_id: 145343622317172
    app_secret: bd6476438158a450568b75e82b7a4304
