defaults: &defaults
  facebook:
    app_id: "145343622317172"
    app_secret: "bd6476438158a450568b75e82b7a4304"
  stripe:
    public_key: "pk_test_B86VL4gz8MTalpfcaRc4paiP"
    private_key: "sk_test_1XLNZlt83RDDPqRIO7EiWoCm"
  google:
    maps_key: "AIzaSyC5nbu6QghhMZ7nUg8KppPc--tPG1QFWkA"
production:
  <<: *defaults
staging:
  <<: *defaults
test:
  <<: *defaults
